### ISSUE TITLE
Video Quality 

### ISSUE THREAD

**Issue by K1nd3r0** [AnthonyGress/Youtube-Downloader#4]
Hello! Can I set the quality at which the videos are downloaded? Or is there a setting to automatically download them in 1080p?

**Comment by AnthonyGress** [comment]
> Hello! Can I set the quality at which the videos are downloaded? Or is there a setting to automatically download them in 1080p?

Hey there, it automatically chooses the best available video for download. I will add a quality selection feature in the future.
